### ISSUE TITLE
Inconsistent eventhub naming in instructions, does not match expectations in source code

### ISSUE THREAD

**Issue by toolboc** [Azure/CloudIoTHack#12]
In [HOL4 - Exercise 1 : Connect the Azure Function to the shared input hub](HOL3 "Exercise 1: Connect the Azure Function to the shared input hub"), the user is instructed to add the following to the function Run method:
`[EventHub("sharedouteventhub", Connection = "SharedEventHubConnection")] IAsyncCollector<string> sharedOutputMessage,`

However, the AirTraffic Sim Source does not expect an EventHub with name "sharedouteventhub" to exist, it rather expects one by name of "flysim-shared-input-hub" as directed in [HOL3 - Exercise 1: Create Event Hubs for input and output - Step 7](https://github.com/Azure/CloudIoTHack/blob/master/HOL%203/HOL%203%20-%20Stream%20Analytics.md#exercise-1-create-event-hubs-for-input-and-output]) and as also indicated in the [Air Traffic Sim source code](https://github.com/Azure/CloudIoTHack/blob/master/AirTrafficSim/AirTrafficSim/Common/CoreConstants.cs#L12).

As a result, the proper modification to the function Run method should look like:
`[EventHub("flysim-shared-input-hub", Connection = "SharedEventHubConnection")] IAsyncCollector<string> sharedOutputMessage`

It is very important to note that with this change to the function annotation, the function will use an entity path of "flysim-shared-input-hub" provided that an entity path is not specified in the connection string supplied to AppSettings.

This occurs because [HOL3 - 
Exercise 1: Create Event Hubs for input and output](https://github.com/Azure/CloudIoTHack/blob/master/HOL%203/HOL%203%20-%20Stream%20Analytics.md#exercise-1-create-event-hubs-for-input-and-output) in step 11 implies that the proctor should copy the connectionstring for the Event Hub namespace without an appended entity path of "flysim-shared-input-hub". 

i.e. this step will generate a connection string for the eventhub namespace and will not contain an entity path => 
![image](https://user-images.githubusercontent.com/2018336/56853041-1c6b3480-68e8-11e9-9355-fdc9660cea2a.png)

If the proctor supplies attendees with a  connectionstring that contains an entity path="flysim-shared-input-hub", the function code will work without modification and will also work when supplied to the Flysim app, but... it is important to note that the only reason this works is because the entity path in the connection string gets overwritten when the attendee follows [HOL4 - Exercise 2: Connect the client app to the shared output hub](https://github.com/Azure/CloudIoTHack/blob/master/HOL%204/HOL%204%20-%20Putting%20It%20All%20Together.md#exercise-2-connect-the-client-app-to-the-shared-output-hub) to create the AirTrafficListener.  

This specific line contains a side-effect which overwrites any pre-existing entity path in the connection string:
`            this.client = EventHubClient.CreateFromConnectionString(Common.CoreConstants.SharedAirTrafficEventHubEndpoint, Common.CoreConstants.SharedAirTrafficHubName);` 

This is a bit confusing, because the function code will only work without modification if a  connectionstring with an entitypath="flysim-shared-input-hub" is supplied, which is not clear in the HOL3 instructions.  While this fixes the function code without any modification, it only works in the Flysim app because the entitypath gets overwritten.   

It is suggested to either change the function code to use the eventhub namespace connection without an entity path as the HOL3 instructions imply by using the modification to function annotation proposed earlier AND if it is decided to go this route it wouldn't be a bad idea to modify [HOL2 - 
Exercise 2: Deploy the Azure Function to transform data](https://github.com/Azure/CloudIoTHack/blob/master/HOL%202/HOL%202%20-%20Functions%20and%20Event%20Hubs.md#exercise-2-deploy-the-azure-function-to-transform-data) to also use a connectionstring without an entity path specified (i.e. the connectionstring to the namespace itself) by modifying the function annotation of "outeventhub" to "flysim".  This will make the evenhub connection strings consistent (no more need for explicit entity path in connection strings)and works without the aid of a side-effect. 

OR

 Update the HOL3 instructions to very clearly indicate that the proctor should copy a connectionstring which contains an entity path of "flysim-shared-input-hub" and be aware that the only reason [HOL4 - 
Exercise 2: Connect the client app to the shared output hub](https://github.com/Azure/CloudIoTHack/blob/master/HOL%204/HOL%204%20-%20Putting%20It%20All%20Together.md#exercise-2-connect-the-client-app-to-the-shared-output-hub) works in the Flysim app is because "flysim-shared-input-hub" gets overwritten to "flysim-shared-output-hub" which just doesn't smell right.

**Comment by lirenhe** [comment]
Fixed. @toolboc , please have a try and let me know if you face any issues.
